GET http://localhost:5000/api/authors
###
GET http://localhost:5000/api/authors/23
###
POST http://localhost:5000/api/authors/
Content-Type: application/json

    {
        "full_name": "Lucius Annaeus Seneca",
        "email": "l-a-s@example.com",
        "nationality": "IT"
    }
###
DELETE http://localhost:5000/api/authors/22
###
PUT http://localhost:5000/api/authors/
Content-Type: application/json

    {
        "id": 23,
        "full_name": "Ishida Sui",
        "email": "sotonami@example.com",
        "nationality": "JP"
    }
